apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: sdn-controller
  name: onos-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      sdn-controller: onos
  template:
    metadata:
      labels:
        sdn-controller: onos
    spec:
      containers:
      - env:
        - name: ONOS_APPS
          value: openflow,ovsdb
        image: onosproject/onos:2.5.0
        name: onos-demo
        stdin: true
        tty: true
