apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deployment: sdn-controller
  name: odl-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      sdn-controller: tpce
  template:
    metadata:
      labels:
        sdn-controller: tpce
    spec:
      containers:
      - env:
        - name: TPCE_APPS
        image: ofcdemo/tpce:2.1.3
        name: tpce-demo
        stdin: true
        tty: true
